// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ColorMerch struct {
	ID    int32  `json:"id"`
	Color string `json:"color"`
}

type Gender struct {
	ID     int32  `json:"id"`
	Gender string `json:"gender"`
}

type MaterialMerch struct {
	ID       int32  `json:"id"`
	Material string `json:"material"`
}

type Merch struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Count       int32       `json:"count"`
	Description string      `json:"description"`
	TypeID      int32       `json:"type_id"`
	SizeID      int32       `json:"size_id"`
	ColorID     int32       `json:"color_id"`
	PhotoID     int32       `json:"photo_id"`
	MaterialID  int32       `json:"material_id"`
	Gender      pgtype.Int4 `json:"gender"`
}

type Order struct {
	ID          int32            `json:"id"`
	UsersID     int32            `json:"users_id"`
	MerchID     int32            `json:"merch_id"`
	TimeOrder   pgtype.Timestamp `json:"time_order"`
	FinishOrder pgtype.Timestamp `json:"finish_order"`
}

type PhotoMerch struct {
	ID    int32  `json:"id"`
	Photo string `json:"photo"`
}

type SizeMerch struct {
	ID   int32  `json:"id"`
	Size string `json:"size"`
}

type TypeMerch struct {
	ID   int32  `json:"id"`
	Type string `json:"type"`
}

type User struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	HashPassword string `json:"hash_password"`
	Phone        string `json:"phone"`
	Email        string `json:"email"`
}
