// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ColorMerch struct {
	ID    int32
	Color string
}

type Gender struct {
	ID     int32
	Gender string
}

type MaterialMerch struct {
	ID       int32
	Material string
}

type Merch struct {
	ID          int32
	Name        string
	Count       int32
	Description string
	TypeID      int32
	SizeID      int32
	ColorID     int32
	PhotoID     int32
	MaterialID  int32
	Gender      pgtype.Int4
}

type Order struct {
	ID          int32
	UsersID     int32
	MerchID     int32
	TimeOrder   pgtype.Timestamp
	FinishOrder pgtype.Timestamp
}

type PhotoMerch struct {
	ID    int32
	Photo string
}

type SizeMerch struct {
	ID   int32
	Size string
}

type TypeMerch struct {
	ID   int32
	Type string
}

type User struct {
	ID           int32
	Name         string
	HashPassword string
	Phone        string
	Email        string
}
